name = "a0b_stm32g474_selftest"
description = "STM32G474 base support sefltest"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files = ["a0b_stm32g474_selftest.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_stm32g474 = "*"
gnat_arm_elf = "*"

[[pins]]
a0b_stm32g474 = { path='..' }
